version: '0.2'

phases:
  install:
    commands:
      - "npm i"
  build:
    commands:
      - "npm run build"
      - "$functionURL > functionURL.txt"
artifacts:
  base-directory: "dist"
  files: 
    - "**/*"